### ISSUE TITLE
Headset support flaky

### ISSUE THREAD

**Issue by pinaraf** [Biktorgj/pinephone_modem_sdk#102]
Hello

I don't often use the phone while holding it (too big and heavy for both my taste and my broken arm), so I tend to use a headset as much as possible.
I notice the support for headset is very flaky. Often the speaker works but the mic won't. Or sometimes neither work, and I have to quickly unplug and replug it to have it used by the modem, making me lose many calls.
What kind of log shall I provide in order to help understand the issue here? I'm using the latest 0.6.5 firmware, but I always had this issue with this firmware (and I had far too many issues with the proprietary firmware before).

Regards

**Comment by Piraty** [comment]
that's an issue to throw at your phone's distro and their alsa/pulse/pipewire/whatever profiles

**Comment by Biktorgj** [comment]
The only thing the modem does is send audio to the host, but whatever happens from there is a task for the distro and kernel on the Pinephone/Pro.

From what you say, it seems to me more like a distro issue than a profile thing, as it does work on unplug/replug
