### ISSUE TITLE
Upgrading to 0.6.6 then 0.6.7 from 0.6.5 on PP resulted in Double Texting/calling

### ISSUE THREAD

**Issue by bakerk98** [Biktorgj/pinephone_modem_sdk#118]
I upgraded from 0.6.5 to 0.6.6 on my PP and I found that in texting people, messages would be received by the people I message, and then about 1 minute later, received again. The same behavior can be observed with calling. This occurred on >0.6.5 and after reverting to 0.6.5, has gone away

PP, AT&T. Please let me know what logs I can post! Thank you

**Comment by Biktorgj** [comment]
This should have been fixed in 0.6.7, did you get the same problem with that version?

**Comment by bakerk98** [comment]
I believe I improperly upgraded. I apologize, but this must have been user error. I reflashed back to 0.6.7 and haven't had any problems
