### ISSUE TITLE
modem temperature reporting too sensitive

### ISSUE THREAD

**Issue by reivanen** [Biktorgj/pinephone_modem_sdk#123]
Since the introduction of temperature reporting via SMS, it is annoying to use the PP as many normal usage patterns result in a text message every 5 minutes. This includes listening to youtube videos with the screen turned off, not charging. But also just downloading things, running pacman update etc. The reported temperature has been 71 or 72 degrees, with ambient temperature 27 degrees.

I would appreciate if the first warning level was increased to at least 74 degrees. How is this current level supposed to work in a country with ambient temperature 35 degrees? The modem would constantly complain no matter what you did with it.

**Comment by Biktorgj** [comment]
Sorry for the delay, I changed thresholds for the temperature triggers and I'm currently testing it. Summer here but reported temperatures for today are 13-18C so some things are hard to trigger :)

For reference, these are the new trigger points: https://github.com/Biktorgj/meta-qcom/blob/8a4af1a2eddd7ed7eb18639bff6600b901ebcf15/recipes-modem/openqti/files/inc/thermal.h#L12

**Comment by reivanen** [comment]
I really appreciate the work you do, and also that the modem won't be complaining after next update
