### ISSUE TITLE
ppp - incoming call ring

### ISSUE THREAD

**Issue by henrythemouse** [Biktorgj/pinephone_modem_sdk#125]
Hi,

I don't even know if the modem has anything to do with the incoming ring. Let  know if it doesn't. 

When a call comes in the phone starts vibrating and ringing without any pauses, It's a constant stream of vibration and ring. I wonder if this can be user configured? Hard coded?

Thanks

**Comment by Biktorgj** [comment]
I think this may be handled in either gnome-calls or feedbackd, _or_ gnome-calls requests that specific mode to feedbackd (the latter seems to do the actual job, and it seems to have support for different modes) but I'm not sure.
In any case, the modem doesn't do anything with it, just says "Hey! there's an incoming call", the phone does everything else :)
