### ISSUE TITLE
can't get a gps fix location on 0.6.6

### ISSUE THREAD

**Issue by sbe-arg** [Biktorgj/pinephone_modem_sdk#132]
unsure what I'm doing wrong but the gps fix never happens

on mobian edge from journalctl

```
Successfully sent command: AT+QCFG="fast/poweroff"
Response: [ERROR]

Command QCFG retried 4 times. aborting...
```

have tried setting `sudo mmcli -m any --command='AT+QCFG="1"'` but getting: cannot sent AT command to modem, operation only allowed in debug mode.

been also triying
- setting up gpsd
- disabling agps with mmcli commands
- reinstalling mobian

i can only get ip location to work atm

**Comment by sbe-arg** [comment]
same in 0.6.6 and 0.6.7

**Comment by sbe-arg** [comment]
I think is a mobian problem I do get a fix on postmarketos and manjaro

Ill do further testing

**Comment by Biktorgj** [comment]
Could be a timing issue at boot, because the AT interface is being used by the modem, ModemManager and eg25-manager at the same time. Will try to push 0.6.8 tomorrow with an attempt to fix that

**Comment by sbe-arg** [comment]
Awesome! Ill try 0.6.8

**Comment by sbe-arg** [comment]
Reporting back... much much better got a fix in ~10min
