### ISSUE TITLE
No recovery.img?

### ISSUE THREAD

**Issue by phs** [Biktorgj/pinephone_modem_sdk#139]
While looking at the [flashing instructions][0] I noticed there's no `recovery.img` in the release.  I also didn't see something with that name over in the mentioned [recovery repo][1].

Where should we find that file?

Thank you also for the great work.

[0]: https://github.com/the-modem-distro/pinephone_modem_sdk/blob/ce07792fac3fa45e9ad806417273966bb8579c83/docs/FLASHING.md?plain=1#L53
[1]: https://github.com/Biktorgj/quectel_eg25_recovery

**Comment by Biktorgj** [comment]
You're absolutely right, just fixed it in the doc.
Please use `fastboot flash recovery mdm9607-boot.img` or `fastboot flash:raw recovery mdm9607-boot.img` 
Sorry for that!
