### ISSUE TITLE
I cannot call or receive calls

### ISSUE THREAD

**Issue by aka0kuro** [Biktorgj/pinephone_modem_sdk#141]
I have a problem with calls and I would like you to help me to solve it. Thanks in advance. 
When I call from my mobile to another device, the call hangs up, directly. And when they call me, the call is busy all the time, although I have mobile data and receive SMS. 
I use pinephone with postmarketos, but it has also happened to me with manjaro. 
I don't know where the problem may lie...

**Comment by Biktorgj** [comment]
You were never able to place calls or is that something that only happens with the custom firmware?

**Comment by aka0kuro** [comment]
No. Before, I could make calls, but this problem happens since I put the custom firmware

**Comment by aka0kuro** [comment]
I have already found the solution, it is because I had 4G alone, by putting 3G the problem is solved.
