### ISSUE TITLE
[Question] Do we need custom kernel flashing this release?

### ISSUE THREAD

**Issue by PsychoGame** [Biktorgj/pinephone_modem_sdk#15]
I downloaded this new release package, and extracted it's contents to study what was inside.
I'm using Manjaro ARM distro, so using Mobian kernel would not be right for my distribution.
If I'm correct the kernel is not included in the flash script provided in the installation package is it?
Do you really need the patched kernel for this modem firmware to work, or does stock kernel work as well for use with the standard sample rates?
Waiting for your reply.

Greetings Jasper

**Comment by Biktorgj** [comment]
Hi Jasper, sorry for late reply, I hadn't seen the issue... 
No, you don't need any custom kernels for any of the releases. You only need that custom kernel if you want to play around switching the audio quality of the modem

**Comment by PsychoGame** [comment]
I'll close this issue, as you have provided me already with the requested information. Maybe handy to put this info in the release notes as well to prevent this question arising again.
