### ISSUE TITLE
cant find saved calls

### ISSUE THREAD

**Issue by bgkillas** [Biktorgj/pinephone_modem_sdk#171]
the modem is saying it saved calls to /tmp/...wav but there is no file there maybe its because i have a tmpfs mounted and its not writing to the tmpfs? pmos, ppp

**Comment by QC8086** [comment]
The recordings are stored on the modem itself. You will need to retrieve them from there. The easiest way I can think of is to enable adb on the modem with [AT+ADBON](https://github.com/the-modem-distro/pinephone_modem_sdk/blob/kirkstone/docs/AT_INTERFACE.md) and then `adb pull /tmp/whatever.wav`.

**Comment by Biktorgj** [comment]
You also have a reference script to retrieve all the recordings here: https://github.com/the-modem-distro/pinephone_modem_sdk/blob/kirkstone/tools/helpers/retrieve_recordings/get_recordings

**Comment by bgkillas** [comment]
yep maybe mention that its in the modems storage in the message enabling it

**Comment by baptx** [comment]
To be able to use adb, I also had to add udev rules to fix a permissions error (tested with the PinePhone on Mobian 12):
https://stackoverflow.com/questions/53887322/adb-devices-no-permissions-user-in-plugdev-group-are-your-udev-rules-wrong
Note that there are errors you may want to fix in the get_recordings script:
https://github.com/the-modem-distro/pinephone_modem_sdk/issues/241
