### ISSUE TITLE
flashall: /dev/ttyUSB2: Device or resource busy

### ISSUE THREAD

**Issue by ghost** [Biktorgj/pinephone_modem_sdk#18]
When running the `flashall` script while the modem is connected, it says the device or resource is busy on the first step:

```
kevin@pinephone:~/Downloads/modem-firmware$ echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2
-bash: /dev/ttyUSB2: Apparaat of hulpbron is bezig
```

(My user is in the `dialout` group.)

Running it as root does work as expected.

As this is the only command that has to be run as root, I'd suggest changing it to:

`sudo su -c 'echo -ne "AT+QFASTBOOT\r" > /dev/ttyUSB2'`

That way, rebooting to fastboot should always work.

**Comment by Biktorgj** [comment]
I need some sleep... 

Updated the script, thanks!
