### ISSUE TITLE
Problems with donations on KoFi (card payments)

### ISSUE THREAD

**Issue by tmczar** [Biktorgj/pinephone_modem_sdk#192]
I'm trying to buy a coffee on KoFi, using "pay with card" option. Sadly, i'm getting this cryptic error:

![image](https://user-images.githubusercontent.com/43699442/222394180-a845f0c2-45c6-430a-b053-64205ba33940.png)

It seems like Stripe account is misconfigured, or something like that (i'm not an expert on internet payments).

**Comment by Biktorgj** [comment]
Hi and thanks for the support!
Unfortunately, Stripe doesn't really work for me. I've sent them every document they asked for but they still have me as "unverified". I don't know, they may need a blood sample or something. Everytime I send them some document it works for a few days, then back to "needs verification or payments will stop working". So I just disabled it

**Comment by tmczar** [comment]
Thanks for clarification. Adding this info to README may be good idea.
