### ISSUE TITLE
Can this firmware support RNDIS/ECM/NCM interface?

### ISSUE THREAD

**Issue by tinnnysu** [Biktorgj/pinephone_modem_sdk#194]
I would like to user RNDIS interface，but I can‘t manage to use it, Would someone give me some suggestion? thanks

**Comment by Biktorgj** [comment]
Hi!
I added a small document with some instructions, let me know if they work for you: https://github.com/the-modem-distro/pinephone_modem_sdk/blob/kirkstone/docs/Internal_Networking_Example.md

**Comment by tinnnysu** [comment]
I successful enable internal net，but I forget to set apn, no internet from rndis. After that my modem manger gui keep crashing, is there a method to reset this setting?
update:
I recovery this setting by mmcli, later I will update the test result

**Comment by tinnnysu** [comment]
rmnet0 doesn't show up on the modem，is there a dial command？
update:
After I fix modem manager gui crash, I send ifup to start the network, it works! Thanks

**Comment by TimelessNL** [comment]
Hi @Biktorgj,

I was reading your [Internal_Networking_Example.md](https://github.com/the-modem-distro/pinephone_modem_sdk/blob/kirkstone/docs/Internal_Networking_Example.md) to enable local networking on a SIM7600X  (_same chipset_) flashed with 0.8.0. But it is unclear to me what the chat application runs to configure the rmnet0 interface. On the original SIMcom firmware I was able to use `AT+CUSBPIDSWITCH=9011,1,1` to setup a RNDIS connection but that obviously does not work with the alternative firmware. Could you please explain the example a little bit more?

**Update:**
After looking at the much appreciated [diagram](https://github.com/the-modem-distro/pinephone_modem_sdk/issues/140#issuecomment-1241484177) and taking a look at [the code](https://github.com/the-modem-distro/meta-qcom/blob/790adee13a5a66483490f974cb6d3f5b0f86a999/recipes-modem/openqti/files/src/config.c#L270) I finally noticed I could directly edit `/persist/openqti.conf` over the `adb shell` to enable the local interface by settings `allow_internal_modem_connectivity=1`. This gave me the `rndis0` interface on the modem and an `ethX` interface on the linux machine it was installed in to communicate locally. Great!

Suggestion from my side, it would be nice to have this mentioned in the doc as well 😄
