### ISSUE TITLE
the newest version 0.2.8 is incompatible with plasma mobile

### ISSUE THREAD

**Issue by Idcrafter** [Biktorgj/pinephone_modem_sdk#23]
it shows up and i even tried downgrading to 0.2.7 and then reinstalling plasma mobile but it only shows this 
![Screenshot_20210806_222712](https://user-images.githubusercontent.com/50270538/128568055-97fe1811-45bf-4949-89ad-acabf7bc501a.png)

and this 
![Screenshot_20210806_222719](https://user-images.githubusercontent.com/50270538/128568113-76f0a84e-8bc8-485d-891a-b527ca2a631a.png)

and if i call the number the phone screen just turns on

**Comment by Biktorgj** [comment]
I know, currently testing some patches for it, see issue #22 
There's a test build in there you might want to flash on top of latest prerelease version to try it out, but so far it's a WIP (I don't loose network info but I can't call in pmOS edge)

**Comment by PsychoGame** [comment]
@Biktorgj, just a heads up in case you missed it in my edited report in my issue report #22.
On Plasma Mobile Manjaro I'm able to make and receive calls fine with the test build you provided.
Maybe check that one out as well, at least then you're not chasing a non existing bug in modem FW.
Maybe it's just a problem in pmOS itself?

**Comment by Idcrafter** [comment]
the newest release has fixed it thanks
