### ISSUE TITLE
Modem status now always says 3G

### ISSUE THREAD

**Issue by vandys** [Biktorgj/pinephone_modem_sdk#27]
Modem seems to work OK, but status bar always shows 3G as status.  I'm in an LTE area, and the original firmware didn't exhibit this behavior?

**Comment by Biktorgj** [comment]
The opensource doesn't do anything that could trigger that by itself.. What distro are you running?

**Comment by vandys** [comment]
Mobian, buster, fully updated.  And now, after a deep sleep, it came back up with 4G!  So dunno.
