### ISSUE TITLE
Revert to stock firmware with fastboot

### ISSUE THREAD

**Issue by Silent-Hunter** [Biktorgj/pinephone_modem_sdk#29]
I feel I need to go back to the stock firmware, can I just use fastboot like I did to flash yours? Or do I have to take the phone apart?

**Comment by Silent-Hunter** [comment]
I've also heard qfirehose will work without bridging pins if the modem is not bricked. But it seems to not be working.

**Comment by Silent-Hunter** [comment]
I'm sorry, I found the instructions you wrote.

**Comment by twiclo** [comment]
Where are those instructions?

Edit: Found it
https://github.com/Biktorgj/pinephone_modem_sdk/blob/kirkstone/docs/RECOVERY.md
