### ISSUE TITLE
easy detection of custom firmware version

### ISSUE THREAD

**Issue by nesnera** [Biktorgj/pinephone_modem_sdk#38]
It would be nice to be able to easily check which version of custom firmware is currently installed.

**Comment by ghost** [comment]
`adb shell openqti -v` ?

**Comment by PsychoGame** [comment]
I think this issue can be closed to be honest.
It's indeed already easy to check open FW version.
Maybe put it in a generic README somewhere.

**Comment by nesnera** [comment]
Yes, `adb shell openqti -v` works. 🥂
Adding it to the README would be nice.

**Comment by Biktorgj** [comment]
Starting from 0.5.0 you can also use AT+GETSWREV to get the current version (added to docs/AT_INTERFACE.md)
