### ISSUE TITLE
Changing IMEI

### ISSUE THREAD

**Issue by pizdjuk** [Biktorgj/pinephone_modem_sdk#39]
I didnt find how to make a feature request, so I write it here:

it would be great if the open firmware would support IMEI change.
The stock firmware can do it with the command: AT+EGMR=1,7,"wishedIMEI"

**Comment by TAAPArthur** [comment]
May I ask why you want this? I want to know if I secretly want this too but currently don't know what effect changing it has.

**Comment by Biktorgj** [comment]
Unfortunately, changing a device's IMEI is illegal in most countries. I haven't tried that command myself but if it works in stock there's probably no reason for it to not work in the custom firmware, since it should be provided by the ADSP.

In any case, if it doesn't work out of the box I can't implement it either

**Comment by pizdjuk** [comment]
Because in many countries the phones simply dont work without register it. For example in many countries of South America, and Turkey. So every time you come to the country its a long process of verification. And normally then you go to the bazar or othe market place and some street-mobile-repair-guy does it for you.

So, this would simply be the great help not to waste time and money.

**Comment by Biktorgj** [comment]
Can confirm the command works perfectly fine,

AT+GSN -> Show current IMEI
AT+EGMR=1,7,"new imei" -> Changes it
AT+GSN -> Check the changed IMEI

So, on par with stock

**Comment by pizdjuk** [comment]
If somebody runs in problems doing it: before doing the steps above -- pull the sim-card out. With a sim-card in you could get en error and IMEI will not change.
