### ISSUE TITLE
can't get the dmesg from modem

### ISSUE THREAD

**Issue by pizdjuk** [Biktorgj/pinephone_modem_sdk#41]
after excecuting

echo -ne "AT+ADBON\r" > /dev/ttyUSB2

device appears in adb devices but with 

no permissions; see [http://developer.android.com/tools/device.html]

So the adb shell dont work. Any idea how to get into the modem?

**Comment by Biktorgj** [comment]
First time you run an ADB command you must be running it as root. run `adb kill-server` and then `sudo adb devices` to force the ADB server running in the pinephone to start as root, then you can run whatever adb command you need as a normal user
