### ISSUE TITLE
USB Reset - A Possible Clue

### ISSUE THREAD

**Issue by ndf-zz** [Biktorgj/pinephone_modem_sdk#64]
Is is possible there is some sort of watchdog or maybe a buffer problem with the AT command port? I was having persisitent USB reset drama, but the following command completely mitigated the problem:

  `# while true ; do echo ATI | atinout - /dev/EG25.AT - ; sleep 2 ; done`

Simply listening to the output (eg):

  `# hd /dev/EG25.AT`

was not enough, but the ATI in a loop (embarrassingly) works really well.

**Comment by Biktorgj** [comment]
You will probably have a similar result just by disabling runtime suspend in the modem USB port:
Open `/usr/lib/udev/rules.d/80-modem-eg25.rules` and, in the first line, change "power/control" from `auto` to `on`

That way the Pinephone won't try to suspend the usb port while the phone is awake, should remove most of the problems, without having to constantly send stuff to the AT port :)

**Comment by ndf-zz** [comment]
Confirmed: setting "power/control" to "on" fixed the USB reset problems I was having. Thanks!
