### ISSUE TITLE
Interference between call and internet connection

### ISSUE THREAD

**Issue by nesnera** [Biktorgj/pinephone_modem_sdk#67]
I often use PP as a WiFi hotspot to connect my laptop to the Internet. I have noticed that during a call (even a ringtone is sufficient) the internet is unavailable. After the call/ring the connection is restored. Is this a firmware (0.5.5) bug?

**Comment by IntinteDAO** [comment]
LTE doesn't allow call communication by default, and I don't know if this firmware supports Vo-LTE.

**Comment by nesnera** [comment]
@IntinteDAO Thanks for the 100% valid hint. I had to explicitly enable VoLTE with my carrier. Now calls work even when I have "Network Modde" set to "4G Only". @Biktorgj  is to be commended.👍
The problem of simultaneous calls and fast internet connection is thus gone, I'm closing the bug.
