### ISSUE TITLE
LTE signal loss sticky

### ISSUE THREAD

**Issue by SpookySkeletons** [Biktorgj/pinephone_modem_sdk#70]
Complete signal loss inside of deep buildings and rural areas can be fairly sticky so once you emerge again the modem might not reacquire signal in a reasonable time prompting me to restart the phone instead of a 5min wait.

Are there any tunables related to aggression of signal acquisition?

**Comment by Biktorgj** [comment]
Not that I know of, there are settings to change the bands and priorities of each, or to lock the modem to certain ones, but "scan times" I haven't seen a way to configure them.

Next time it happens you might want to try disabling and re-enabling network (if using Phosh, go to Settings -> Mobile Network and switch the Mobile network toggle off, wait a few seconds, and turn it on again). That should issue a disconnect and reconnect to the modem

**Comment by SpookySkeletons** [comment]
Updated my modem blob to the very latest and I have to say its a huge improvement. Signal falls off and comes back quite quickly now, do recommend the latest blob in the readme if not already, t-mobile if it matters.

**Comment by DylanVanAssche** [comment]
@SpookySkeletons Would you mind to add your findings here: https://github.com/Biktorgj/pinephone_modem_sdk/blob/honister/docs/ADSP-CARRIERS.md ?
