### ISSUE TITLE
Braveheart stuck at "Sending AT+QFASTBOOT... < waiting for any device >" modem in failed state

### ISSUE THREAD

**Issue by fbmoose48** [Biktorgj/pinephone_modem_sdk#71]
I have a Braveheart on Arch Phosh I'm trying to flash the latest 0.5.9 FW on. when I run the `flashall` comand it gets stuck on
```
Sending AT+QFASTBOOT...
< waiting for any device >
```
Not sure how to resolve this.
`adb devices` returns
```
* daemon not running; starting now at tcp:5037
* daemon started successfully
List of devices attached


```
and `fastboot devices` returns nothing
`lsusb` does return
`Bus 002 Device 002: ID 2c7c:0125 Quectel Wireless Solutions Co., Ltd. EC25 LTE modem`
so the modem does appear to be there but `sudo mmcli -m any -e` returns
```error: couldn't enable the modem: 'GDBus.Error:org.freedesktop.ModemManager1.Error.Core.WrongState: modem in failed state'```
how might I get out of this failed state?

**Comment by Biktorgj** [comment]
First question, were you running the `flashall` script as root? 
You can also try to send the command directly from the shell and see if it behaves differently: ` echo -e "AT+QFASTBOOT\r\n" > /dev/ttyUSB2` 
Last thing I can think of with the provided info is that ModemManager might have the port blocked, you can try stopping it first then attempt to flash it (`systemctl stop ModemManager)` but I don't think that's the case.

ADB is not enabled by default, you need to turn it on wiht `AT+ADBON`, so it makes sense that it says that if you never used it before

**Comment by fbmoose48** [comment]
My modem seemed to be frozen. I had a systemd service/timer running an "AT+CMGD=0,4" command on the modem that seemed to get hung after a few weeks. I resolved by 1) stopping the service/timer 2) rebooting 3) rebooting again with the modem dip switch off and 4) rebooting again with modem dip switch on. I was then able to set modem to FASTBOOT mode and flash as instructed. Thanks

**Comment by castenaso** [comment]
How can i 1) stopping the service/timer ? i cant fastboot my pinephone
