### ISSUE TITLE
documentation: adsp carrier list

### ISSUE THREAD

**Issue by joergsch** [Biktorgj/pinephone_modem_sdk#79]
Please add
country: Germany
Carrier: 1&1 (using Telefonica network)
ADSP version: 30.004, 01.003 -- both versions worked well

**Comment by Biktorgj** [comment]
Added the carrier to the list (https://github.com/Biktorgj/pinephone_modem_sdk/commit/e70cd1c28036282d923d4e9e924816de57b70981)

Thanks for the report!
