### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by SpookySkeletons** [Biktorgj/pinephone_modem_sdk#87]
Is it currently possible to easily forward a port on the modem to the phone itself without having to build new firmware?

Are ISPs iffy about lte ports?

**Comment by Biktorgj** [comment]
The modem binds the public IP given by the network directly to the host, so, unless you have a firewall setup in your phone it should work... *unless* you're behind carrier NAT (CG-NAT) which is actually the default for most carriers. I've only seen lines outside of CGNAT with custom (read expensive) business class lines for enterprise fiber failover and stuff like that

**Comment by SpookySkeletons** [comment]
Question answered closing.
